
# VMWare Host inventory collector configuration
# Enter the information for vCenter login account and target vm
# 
# example:
#
# url = "https://192.168.10.100/sdk"  # vCenter URL
# user = "test_user"
# password = "P@ssword"
# server = "esxi"                     # esxi host name

url = "https://192.168.10.100/sdk"
user = "test_user"
password = "P@ssword"
server = "192.168.10.100"

# The following parameters are optional

# Additional metrics list of VMWare Managed Object. 
# 
# Reference : https://code.vmware.com/apis/42/vsphere/doc/vim.HostSystem.html
# 
# example:
#
# metrics = ["config", "vm", "systemResources", "runtime"]

# List of monitored servers other than the local server
#
# example:
#
# servers = ["host1", "host2"]
